import 'dotenv/config';
import { upsertInstallation } from '../src/db';

// Token data from the OAuth exchange
const tokenData = {
  access_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoQ2xhc3MiOiJMb2NhdGlvbiIsImF1dGhDbGFzc0lkIjoiUlpCRjhKNDU1aEhjTXdFOW56aG0iLCJzb3VyY2UiOiJJTlRFR1JBVElPTiIsInNvdXJjZUlkIjoiNjhlZTc3MGFiODJhY2ViNjdiZmFhZTYwLW1nczhpNWcyIiwiY2hhbm5lbCI6Ik9BVVRIIiwicHJpbWFyeUF1dGhDbGFzc0lkIjoiUlpCRjhKNDU1aEhjTXdFOW56aG0iLCJvYXV0aE1ldGEiOnsic2NvcGVzIjpbImNvdXJzZXMud3JpdGUiLCJjb3Vyc2VzLnJlYWRvbmx5IiwicHJvZHVjdHMvcHJpY2VzLnJlYWRvbmx5IiwicHJvZHVjdHMucmVhZG9ubHkiLCJwcm9kdWN0cy53cml0ZSIsInByb2R1Y3RzL3ByaWNlcy53cml0ZSIsInByb2R1Y3RzL2NvbGxlY3Rpb24ucmVhZG9ubHkiLCJwcm9kdWN0cy9jb2xsZWN0aW9uLndyaXRlIiwicGF5bWVudHMvaW50ZWdyYXRpb24ucmVhZG9ubHkiLCJwYXltZW50cy9zdWJzY3JpcHRpb25zLnJlYWRvbmx5IiwicGF5bWVudHMvY3VzdG9tLXByb3ZpZGVyLnJlYWRvbmx5IiwiYnVzaW5lc3Nlcy5yZWFkb25seSIsImxvY2F0aW9ucy5yZWFkb25seSIsImxvY2F0aW9ucy9jdXN0b21WYWx1ZXMucmVhZG9ubHkiLCJmdW5uZWxzL3BhZ2UucmVhZG9ubHkiLCJmdW5uZWxzL2Z1bm5lbC5yZWFkb25seSIsImZ1bm5lbHMvcGFnZWNvdW50LnJlYWRvbmx5IiwiZnVubmVscy9yZWRpcmVjdC5yZWFkb25seSIsInBheW1lbnRzL29yZGVycy5yZWFkb25seSIsInBheW1lbnRzL3RyYW5zYWN0aW9ucy5yZWFkb25seSJdLCJjbGllbnQiOiI2OGVlNzcwYWI4MmFjZWI2N2JmYWFlNjAiLCJ2ZXJzaW9uSWQiOiI2OGVlNzcwYWI4MmFjZWI2N2JmYWFlNjAiLCJjbGllbnRLZXkiOiI2OGVlNzcwYWI4MmFjZWI2N2JmYWFlNjAtbWdzOGk1ZzIifSwiaWF0IjoxNzYxNjExOTQ1Ljg0MSwiZXhwIjoxNzYxNjk4MzQ1Ljg0MX0.BOY_wrmJ_gaBgSy6ya2lYMNdhgmv7XOhX-4t5gQDBiPcWwHKhasM9UaUY_ZiLWV346VYX5eUZq94ZwdScmtrOu6aCS_Y9dpWSllv6vMCzvr_fbFoY5NwxM-fuE3m437zDiGEkKOsZCapwRcWKfS6FYJta5u6PX2dKZWHRM9OxZIzEK1_D_1PWCK3bXJ0eGyx_HLzfmUg8rpsTa_wup6MieaRlDnPwTg9BHuvoPU0tOBjoBXY22NL6raNWlhsRKw1UsVbvoT9qvS9TVudrF1NbXaYudlvNNmqfqtRR2eMCvZSxiLWpZ89sXmNSsn-F7UgVfuTm5GZAqlc72L6N_ndBtPD_fgA4ROtWlyGubjafyrd3M2FVcETkmFQ-larMOVMkQN0vN1yOlWA973tKPEuj1WPmr3rSxsY0eecDpY43oCtfsOUzfsi5UqpQtdQCq_OiNZDhfnYEtwd3eKsuRkJIihHxOr3kxfs6IIWGdyEy0-cXZpcs6NM7RDjIMYdu9CwCljEfq5rz6CxGp_gwxZU1GzntAuqFq-uoid3UttD8IjikT50dnIN3iUhyEUJoh--bSuncDH9cNTWq69JBKKAE8_EqyyzUpAcXL875A7YZqDX6424xlcWw4aXQUNepaRfxmXr1H5yPz__3-RQSeOWi44WeeAgYUiPxHoj2iI1784",
  refresh_token: "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoQ2xhc3MiOiJMb2NhdGlvbiIsImF1dGhDbGFzc0lkIjoiUlpCRjhKNDU1aEhjTXdFOW56aG0iLCJzb3VyY2UiOiJJTlRFR1JBVElPTiIsInNvdXJjZUlkIjoiNjhlZTc3MGFiODJhY2ViNjdiZmFhZTYwLW1nczhpNWcyIiwiY2hhbm5lbCI6Ik9BVVRIIiwicHJpbWFyeUF1dGhDbGFzc0lkIjoiUlpCRjhKNDU1aEhjTXdFOW56aG0iLCJvYXV0aE1ldGEiOnsic2NvcGVzIjpbImNvdXJzZXMud3JpdGUiLCJjb3Vyc2VzLnJlYWRvbmx5IiwicHJvZHVjdHMvcHJpY2VzLnJlYWRvbmx5IiwicHJvZHVjdHMucmVhZG9ubHkiLCJwcm9kdWN0cy53cml0ZSIsInByb2R1Y3RzL3ByaWNlcy53cml0ZSIsInByb2R1Y3RzL2NvbGxlY3Rpb24ucmVhZG9ubHkiLCJwcm9kdWN0cy9jb2xsZWN0aW9uLndyaXRlIiwicGF5bWVudHMvaW50ZWdyYXRpb24ucmVhZG9ubHkiLCJwYXltZW50cy9zdWJzY3JpcHRpb25zLnJlYWRvbmx5IiwicGF5bWVudHMvY3VzdG9tLXByb3ZpZGVyLnJlYWRvbmx5IiwiYnVzaW5lc3Nlcy5yZWFkb25seSIsImxvY2F0aW9ucy5yZWFkb25seSIsImxvY2F0aW9ucy9jdXN0b21WYWx1ZXMucmVhZG9ubHkiLCJmdW5uZWxzL3BhZ2UucmVhZG9ubHkiLCJmdW5uZWxzL2Z1bm5lbC5yZWFkb25seSIsImZ1bm5lbHMvcGFnZWNvdW50LnJlYWRvbmx5IiwiZnVubmVscy9yZWRpcmVjdC5yZWFkb25seSIsInBheW1lbnRzL29yZGVycy5yZWFkb25seSIsInBheW1lbnRzL3RyYW5zYWN0aW9ucy5yZWFkb25seSJdLCJjbGllbnQiOiI2OGVlNzcwYWI4MmFjZWI2N2JmYWFlNjAiLCJ2ZXJzaW9uSWQiOiI2OGVlNzcwYWI4MmFjZWI2N2JmYWFlNjAiLCJjbGllbnRLZXkiOiI2OGVlNzcwYWI4MmFjZWI2N2JmYWFlNjAtbWdzOGk1ZzIifSwiaWF0IjoxNzYxNjExOTQ1Ljg0OCwiZXhwIjoxNzkzMTQ3OTQ1Ljg0OCwidW5pcXVlSWQiOiJmNGQ3NzNjYS0yMzI3LTQ3YzItOGY4MC01Mzk4YmMxNzhjZDYiLCJ2IjoiMiJ9.c6jOLjQNOXQjge9vMid44RRdH20qu9Rwtksqn04oQiFj02RGQbgdzUTOUIc_PuAqLT3DoMap4jbdREWTw86FsdCAtPgK-aC3uz1Svfyt_XyJtq_AXr3JGmzf-GHQodWBWvgn-gWAmkwYirYhV2zzzrVlU8KI0Y2HrQfbDtlIUWTIO5Y4zFLJIC8OadTDW3R9-0iMmNtwabw2lAjKf3j9pyEtG_w36t3ld2FH7SYgZrTe_IXB8UIe3uP1kFZVw1SnxUncHmLewPtQR6glRWWo8WJ0qAsM2RfwGBnKg4m1rhiNhGcAqTPx9atywIEOQGqBCceX9YDJzPHafBBbiNmbSTPCNG-lwJ2WUqQjK562W0IvhMnQ8jebg9bUH3lf4PeEl1-dq3WBQrYc3UWmxng8QRUUhYMpFYo65ss8KTxKmPsq7jWXw1SbyLCTQtcD_zGo6hp66G9BcGQRXGqHKycG3cfDCqLoizAeaW3oPQp6UCNcEWYbJiJkjPa5tAMJGaxj3Ee04P2Us0uxkCEnEGfwjf3Xq_bYN7LyUD1tIkYLkj_bItrbSmxe2ve_zBDHK9Vl_nNYgO0TDlH-G11Na6JqcABnoeF3ifRbDpirby5myF3vP3XxidetbhHRJuZ_dP8WYRlq6KBgiIUBfXnQ0FyV0uU-9VnP69_UGgUx-Esx5OI",
  expires_in: 86399,
  scope: "courses.write courses.readonly products/prices.readonly products.readonly products.write products/prices.write products/collection.readonly products/collection.write payments/integration.readonly payments/subscriptions.readonly payments/custom-provider.readonly businesses.readonly locations.readonly locations/customValues.readonly funnels/page.readonly funnels/funnel.readonly funnels/pagecount.readonly funnels/redirect.readonly payments/orders.readonly payments/transactions.readonly",
  userType: "Location",
  companyId: "Cbjwl9dRdmiskYlzh8Oo",
  locationId: "RZBF8J455hHcMwE9nzhm"
};

async function storeToken() {
  try {
    console.log('Storing OAuth token in database...');
    console.log('Location ID:', tokenData.locationId);
    console.log('Company ID:', tokenData.companyId);
    
    const installation = await upsertInstallation({
      locationId: tokenData.locationId,
      accountId: tokenData.companyId,
      accessToken: tokenData.access_token,
      refreshToken: tokenData.refresh_token,
      expiresAt: Date.now() + (tokenData.expires_in * 1000),
      scope: tokenData.scope,
      tokenType: 'location'
    });
    
    console.log('✅ Token stored successfully!');
    console.log('Installation:', {
      locationId: installation.locationId,
      accountId: installation.accountId,
      tokenType: installation.tokenType,
      expiresAt: new Date(installation.expiresAt!).toISOString()
    });
    
    process.exit(0);
  } catch (error) {
    console.error('❌ Error storing token:', error);
    process.exit(1);
  }
}

storeToken();

